name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI and Render Deploy"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull debbie919/coursework-group_14:latest
    - name: Delete Old docker container
      run: sudo docker rm -f coursework-group_14-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name coursework-group14-container debbie919/coursework-group_14
